server:
  port: 9000

spring:
  application:
    name: devtools-service
  datasource:
    url: jdbc:mysql://192.168.1.5:3306/yidai_test?autoReconnect=true&useUnicode=true&useSSL=false
    username: yidai_dev
    password: yidai_devmysql
    #    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    db-name: yidai_test
newretail:
  devtools: #开发工具
    project-location: D:/devtools
    developer:
    table-prefix: newretail_


